export const LOGIN_TYPE = 'LOGIN_TYPE'
export const LOGOUT_TYPE = 'LOGOUT_TYPE'

export const ADD_USER_TYPE = 'ADD_USER_TYPE'
export const REMOVE_USER_TYPE = 'REMOVE_USER_TYPE'

export const NEW_MESSAGE_TYPE = 'NEW_MESSAGE_TYPE'
export const SEND_MESSAGE_TYPE = 'SEND_MESSAGE_TYPE'
export const UNREAD_MESSAGE_TYPE = 'UNREAD_MESSAGE_TYPE'

export const INIT_CHAT_TYPE = 'INIT_CHAT_TYPE'
export const CREATE_CHAT_TYPE = 'CREATE_CHAT_TYPE'
export const START_CHAT_TYPE = 'START_CHAT_TYPE'
export const CHANGE_ACTIVE_CHAT_TYPE = 'CHANGE_ACTIVE_CHAT_TYPE'
export const ACTIVE_USER_TYPE = 'ACTIVE_USER_TYPE'
